#!/usr/bin/env python3
"""Shared constants for the enemy parser curation pipeline."""

from __future__ import annotations

from typing import Any, Dict

INTERNAL_RAW_ZONE_NAME_KEY = '_raw_zone_name'
INTERNAL_ZONE_METADATA_KEYS = frozenset({'_raw_zone_name'})

def build_enemy_scope_tags_by_unit_name(
    scope_tag_groups: Dict[str, tuple[str, ...]],
) -> Dict[str, list[str]]:
    scope_tags_by_unit_name: Dict[str, list[str]] = {}
    for scope_tag, unit_names in scope_tag_groups.items():
        for unit_name in unit_names:
            scope_tags_by_unit_name.setdefault(unit_name, []).append(scope_tag)
    return scope_tags_by_unit_name


ENEMY_SCOPE_TAG_GROUPS: Dict[str, tuple[str, ...]] = {
    'chaff': (
        'Assault Raider',
        'Bile Spitter',
        'Brawler',
        'Commissar',
        'Marauder',
        'MG Raider',
        'Pouncer',
        'Pyro Trooper',
        'Raider',
        'Rocket Raider',
        'Scavenger',
        'Scout Raider',
        'Shrieker',
        'Spore Burst Scavenger',
        'Trooper',
        'Voteless',
        'Watcher',
    ),
    'medium': (
        'Berserker',
        'Bile Warrior',
        'Conflagration Devastator',
        'Devastator',
        'Elevated Overseer',
        'Heavy Devastator',
        'Hive Guard',
        'Hunter',
        'Incendiary MG Devastator',
        'Obtruder',
        'Overseer',
        'Predator Hunter',
        'Rocket Devastator',
        'Rupture Warrior',
        'Scout Strider',
        'Spore Burst Hunter',
        'Spore Burst Warrior',
        'Warrior',
    ),
    'elite': (
        'Agitator',
        'Alpha Commander',
        'Bile Spewer',
        'Brood Commander',
        'Crescent Overseer',
        'Gazer',
        'Gunship',
        'Nursing Spewer',
        'Predator Stalker',
        'Radical',
        'Rupture Spewer',
        'Stalker',
        'Stingray',
    ),
    'tank': (
        'Annihilator Tank',
        'Barrager Tank',
        'Charger',
        'Charger Behemoth',
        'Dropship',
        'Fleshmob',
        'Gatekeeper',
        'Hulk',
        'Hulk Bruiser',
        'Hulk Firebomber',
        'Hulk Obliterator',
        'Hulk Scorcher',
        'Reinforced Scout Strider',
        'Rupture Charger',
        'Shredder Tank',
        'Spore Charger',
        'Veracitor',
        'War Strider',
        'Xenobite Ardent',
    ),
    'giant': (
        'Bile Titan',
        'Dragonroach',
        'Factory Strider',
        'Harvester',
        'Hive Lord',
        'Impaler',
        'Leviathan',
        'Vox Engine',
    ),
    'structure': (
        'AA Emplacement',
        'Automaton Mortar Emplacement',
        'Cannon Turret',
        'Factory Strider Gatling Gun',
        'Fusion Autocannon',
        'Fusion Repeater',
        'Heavy Fusion Cannon',
        'Heavy Fusion Repeater',
        'Lightning Spire',
    ),
    'objective': (
        'Ballistic Missile',
        'Bulk Fabricator',
        'Fabricator',
        'Infested Tower',
        'Shrieker Nest',
        'Spore Lung',
        'Warp Ship',
    ),
}

ENEMY_SCOPE_TAGS_BY_UNIT_NAME = build_enemy_scope_tags_by_unit_name(ENEMY_SCOPE_TAG_GROUPS)

# These overrides prefer the raw imported zone_name/ThinHash plus occurrence
# order within matching raw names. They can also fall back to the parser's
# transformed zone signature plus occurrence order for legacy/manual entries.
# This keeps matching fail-closed while still letting curated names survive
# balance-only stat drift when the upstream raw zone anchor stays stable.
CURATED_ZONE_NAME_OVERRIDES_BY_UNIT_NAME: Dict[str, list[Dict[str, Any]]] = {'Agitator': [{'occurrence': 0,
               'zone_name': 'left_forearm',
               'signature': {'AV': 2,
                             'Dur%': 0,
                             'ExTarget': 'Main',
                             'MainCap': True,
                             'ToMain%': 0.75,
                             'health': 300},
               'raw_zone_name': '0x76ac2433'},
              {'occurrence': 1,
               'zone_name': 'right_forearm',
               'signature': {'AV': 2,
                             'Dur%': 0,
                             'ExTarget': 'Main',
                             'MainCap': True,
                             'ToMain%': 0.75,
                             'health': 300},
               'raw_zone_name': '0x44e01906'},
              {'occurrence': 0,
               'zone_name': 'left_upper_arm',
               'signature': {'AV': 1,
                             'Dur%': 0,
                             'ExMult': 0.45,
                             'ExTarget': 'Part',
                             'MainCap': True,
                             'ToMain%': 0.8,
                             'health': 300},
               'raw_zone_name': '0x77e524e5'},
              {'occurrence': 1,
               'zone_name': 'right_upper_arm',
               'signature': {'AV': 1,
                             'Dur%': 0,
                             'ExMult': 0.45,
                             'ExTarget': 'Part',
                             'MainCap': True,
                             'ToMain%': 0.8,
                             'health': 300},
               'raw_zone_name': '0x1d5e82c0'},
              {'occurrence': 0,
               'zone_name': 'head',
               'signature': {'AV': 1,
                             'Dur%': 0,
                             'ExTarget': 'Main',
                             'IsFatal': True,
                             'MainCap': True,
                             'ToMain%': 1,
                             'health': 150},
               'raw_zone_name': '0x19ab8d6e'},
              {'occurrence': 0,
               'zone_name': 'left_leg',
               'signature': {'AV': 2,
                             'Dur%': 0,
                             'ExTarget': 'Main',
                             'IsFatal': True,
                             'MainCap': False,
                             'ToMain%': 0.75,
                             'health': 1400},
               'raw_zone_name': '0xc7624c9c'},
              {'occurrence': 1,
               'zone_name': 'right_leg',
               'signature': {'AV': 2,
                             'Dur%': 0,
                             'ExTarget': 'Main',
                             'IsFatal': True,
                             'MainCap': False,
                             'ToMain%': 0.75,
                             'health': 1400},
               'raw_zone_name': '0x98e7f49c'},
              {'occurrence': 0,
               'zone_name': 'pelvis',
               'signature': {'AV': 2,
                             'Dur%': 0,
                             'ExTarget': 'Main',
                             'IsFatal': True,
                             'MainCap': False,
                             'ToMain%': 1,
                             'health': 1400},
               'raw_zone_name': 'pelvis'},
              {'occurrence': 0,
               'zone_name': 'torso',
               'signature': {'AV': 2,
                             'Dur%': 0,
                             'ExTarget': 'Main',
                             'IsFatal': True,
                             'MainCap': False,
                             'ToMain%': 1,
                             'health': 1200},
               'raw_zone_name': '0x55f196f8'},
              {'occurrence': 0,
               'zone_name': 'torso_armor',
               'signature': {'AV': 2,
                             'Dur%': 0,
                             'ExMult': 0.35,
                             'ExTarget': 'Part',
                             'MainCap': False,
                             'ToMain%': 0.3,
                             'health': 300},
               'raw_zone_name': '0xfb03b8ff'},
              {'occurrence': 0,
               'zone_name': 'helmet',
               'signature': {'AV': 2,
                             'Dur%': 0,
                             'ExMult': 0.35,
                             'ExTarget': 'Part',
                             'MainCap': False,
                             'ToMain%': 0.3,
                             'health': 200},
               'raw_zone_name': '0x698cf267'},
              {'occurrence': 1,
               'zone_name': 'left_pauldron',
               'signature': {'AV': 2,
                             'Dur%': 0,
                             'ExMult': 0.35,
                             'ExTarget': 'Part',
                             'MainCap': False,
                             'ToMain%': 0.3,
                             'health': 200},
               'raw_zone_name': '0xf3c6b261'},
              {'occurrence': 2,
               'zone_name': 'right_pauldron',
               'signature': {'AV': 2,
                             'Dur%': 0,
                             'ExMult': 0.35,
                             'ExTarget': 'Part',
                             'MainCap': False,
                             'ToMain%': 0.3,
                             'health': 200},
               'raw_zone_name': '0x15b3c47f'}],
 'Radical': [{'occurrence': 0,
              'zone_name': 'left_forearm',
              'signature': {'AV': 2,
                            'Dur%': 0,
                            'ExTarget': 'Main',
                            'MainCap': True,
                            'ToMain%': 0.75,
                            'health': 300},
              'raw_zone_name': '0x76ac2433'},
             {'occurrence': 1,
              'zone_name': 'right_forearm',
              'signature': {'AV': 2,
                            'Dur%': 0,
                            'ExTarget': 'Main',
                            'MainCap': True,
                            'ToMain%': 0.75,
                            'health': 300},
              'raw_zone_name': '0x44e01906'},
             {'occurrence': 0,
              'zone_name': 'left_upper_arm',
              'signature': {'AV': 1,
                            'Dur%': 0,
                            'ExMult': 0.45,
                            'ExTarget': 'Part',
                            'MainCap': True,
                            'ToMain%': 0.8,
                            'health': 300},
              'raw_zone_name': '0x77e524e5'},
             {'occurrence': 1,
              'zone_name': 'right_upper_arm',
              'signature': {'AV': 1,
                            'Dur%': 0,
                            'ExMult': 0.45,
                            'ExTarget': 'Part',
                            'MainCap': True,
                            'ToMain%': 0.8,
                            'health': 300},
              'raw_zone_name': '0x1d5e82c0'},
             {'occurrence': 0,
              'zone_name': 'head',
              'signature': {'AV': 1,
                            'Dur%': 0,
                            'ExTarget': 'Main',
                            'IsFatal': True,
                            'MainCap': True,
                            'ToMain%': 1,
                            'health': 150},
              'raw_zone_name': '0x19ab8d6e'},
             {'occurrence': 0,
              'zone_name': 'left_leg',
              'signature': {'AV': 2,
                            'Dur%': 0,
                            'ExTarget': 'Main',
                            'IsFatal': True,
                            'MainCap': False,
                            'ToMain%': 0.75,
                            'health': 1400},
              'raw_zone_name': '0xc7624c9c'},
             {'occurrence': 1,
              'zone_name': 'right_leg',
              'signature': {'AV': 2,
                            'Dur%': 0,
                            'ExTarget': 'Main',
                            'IsFatal': True,
                            'MainCap': False,
                            'ToMain%': 0.75,
                            'health': 1400},
              'raw_zone_name': '0x98e7f49c'},
             {'occurrence': 0,
              'zone_name': 'pelvis',
              'signature': {'AV': 2,
                            'Dur%': 0,
                            'ExTarget': 'Main',
                            'IsFatal': True,
                            'MainCap': False,
                            'ToMain%': 1,
                            'health': 1400},
              'raw_zone_name': 'pelvis'},
             {'occurrence': 0,
              'zone_name': 'torso',
              'signature': {'AV': 2,
                            'Dur%': 0,
                            'ExTarget': 'Main',
                            'IsFatal': True,
                            'MainCap': False,
                            'ToMain%': 1,
                            'health': 1200},
              'raw_zone_name': '0x55f196f8'},
             {'occurrence': 0,
              'zone_name': 'torso_armor',
              'signature': {'AV': 2,
                            'Dur%': 0,
                            'ExMult': 0.35,
                            'ExTarget': 'Part',
                            'MainCap': False,
                            'ToMain%': 0.3,
                            'health': 300},
              'raw_zone_name': '0x15b3c47f'},
             {'occurrence': 0,
              'zone_name': 'helmet',
              'signature': {'AV': 2,
                            'Dur%': 0,
                            'ExMult': 0.35,
                            'ExTarget': 'Part',
                            'MainCap': False,
                            'ToMain%': 0.3,
                            'health': 200},
              'raw_zone_name': '0xfb03b8ff'},
             {'occurrence': 1,
              'zone_name': 'left_pauldron',
              'signature': {'AV': 2,
                            'Dur%': 0,
                            'ExMult': 0.35,
                            'ExTarget': 'Part',
                            'MainCap': False,
                            'ToMain%': 0.3,
                            'health': 200},
              'raw_zone_name': '0x698cf267'},
             {'occurrence': 2,
              'zone_name': 'right_pauldron',
              'signature': {'AV': 2,
                            'Dur%': 0,
                            'ExMult': 0.35,
                            'ExTarget': 'Part',
                            'MainCap': False,
                            'ToMain%': 0.3,
                            'health': 200},
              'raw_zone_name': '0xf3c6b261'}],
 'Impaler': [{'occurrence': 0,
              'zone_name': 'l_tentacle_armor',
              'signature': {'AV': 4,
                            'Dur%': 0.75,
                            'ExTarget': 'Part',
                            'MainCap': True,
                            'ToMain%': 1,
                            'health': -1},
              'raw_zone_name': '0xf7938517'},
             {'occurrence': 1,
              'zone_name': 'm_tentacle_armor',
              'signature': {'AV': 4,
                            'Dur%': 0.75,
                            'ExTarget': 'Part',
                            'MainCap': True,
                            'ToMain%': 1,
                            'health': -1},
              'raw_zone_name': '0x3d0088eb',
              'raw_occurrence': 0},
             {'occurrence': 2,
              'zone_name': 'r_tentacle_armor',
              'signature': {'AV': 4,
                            'Dur%': 0.75,
                            'ExTarget': 'Part',
                            'MainCap': True,
                            'ToMain%': 1,
                            'health': -1},
              'raw_zone_name': '0x3d0088eb',
              'raw_occurrence': 1}],
 'Veracitor': [{'occurrence': 0,
                'zone_name': 'cockpit',
                'signature': {'AV': 3,
                              'Dur%': 0.5,
                              'ExTarget': 'Main',
                              'IsFatal': True,
                              'MainCap': True,
                              'ToMain%': 1,
                              'health': 1600},
                'raw_zone_name': 'pilot_seat'},
               {'occurrence': 0,
                'zone_name': 'cockpit_weakspot',
                'signature': {'AV': 1,
                              'Dur%': 0.5,
                              'ExTarget': 'Main',
                              'IsFatal': True,
                              'MainCap': True,
                              'ToMain%': 1,
                              'health': 800},
                'raw_zone_name': '0x7c69c9f9'},
               {'occurrence': 0,
                'zone_name': 'chassis',
                'signature': {'AV': 3,
                              'Dur%': 0.5,
                              'ExTarget': 'Main',
                              'IsFatal': True,
                              'MainCap': False,
                              'ToMain%': 0.75,
                              'health': 1600},
                'raw_zone_name': '0x6c40f976'},
               {'occurrence': 0,
                'zone_name': 'head',
                'signature': {'AV': 3,
                              'Dur%': 0,
                              'ExTarget': 'Main',
                              'MainCap': False,
                              'ToMain%': 0,
                              'health': 300},
                'raw_zone_name': '0x73757f26'},
               {'occurrence': 0,
                'zone_name': 'left_carapace',
                'signature': {'AV': 3,
                              'Dur%': 0.5,
                              'ExTarget': 'Main',
                              'MainCap': False,
                              'ToMain%': 0.5,
                              'health': 400},
                'raw_zone_name': '0x2119e2ef'},
               {'occurrence': 1,
                'zone_name': 'right_carapace',
                'signature': {'AV': 3,
                              'Dur%': 0.5,
                              'ExTarget': 'Main',
                              'MainCap': False,
                              'ToMain%': 0.5,
                              'health': 400},
                'raw_zone_name': '0x533fbac2'},
               {'occurrence': 0,
                'zone_name': 'left_internals',
                'signature': {'AV': 1,
                              'Dur%': 0.5,
                              'ExTarget': 'Main',
                              'IsFatal': True,
                              'MainCap': False,
                              'ToMain%': 1,
                              'health': 600},
                'raw_zone_name': '0xba20d30a'},
               {'occurrence': 1,
                'zone_name': 'right_internals',
                'signature': {'AV': 1,
                              'Dur%': 0.5,
                              'ExTarget': 'Main',
                              'IsFatal': True,
                              'MainCap': False,
                              'ToMain%': 1,
                              'health': 600},
                'raw_zone_name': '0xe073cc3f'},
               {'occurrence': 0,
                'zone_name': 'pilot',
                'signature': {'AV': 2,
                              'Dur%': 0,
                              'ExTarget': 'Main',
                              'IsFatal': True,
                              'MainCap': True,
                              'ToMain%': 0,
                              'health': 700},
                'raw_zone_name': '0x23128279'},
               {'occurrence': 0,
                'zone_name': 'left_shoulder',
                'signature': {'AV': 2,
                              'Dur%': 0.5,
                              'ExTarget': 'Main',
                              'MainCap': False,
                              'ToMain%': 0.75,
                              'health': 800},
                'raw_zone_name': '0x19c4c9a6'},
               {'occurrence': 1,
                'zone_name': 'left_upper_arm',
                'signature': {'AV': 2,
                              'Dur%': 0.5,
                              'ExTarget': 'Main',
                              'MainCap': False,
                              'ToMain%': 0.75,
                              'health': 800},
                'raw_zone_name': 'left_arm'},
               {'occurrence': 2,
                'zone_name': 'right_shoulder',
                'signature': {'AV': 2,
                              'Dur%': 0.5,
                              'ExTarget': 'Main',
                              'MainCap': False,
                              'ToMain%': 0.75,
                              'health': 800},
                'raw_zone_name': '0x6e41f493'},
               {'occurrence': 3,
                'zone_name': 'right_upper_arm',
                'signature': {'AV': 2,
                              'Dur%': 0.5,
                              'ExTarget': 'Main',
                              'MainCap': False,
                              'ToMain%': 0.75,
                              'health': 800},
                'raw_zone_name': 'right_arm'},
               {'occurrence': 0,
                'zone_name': 'left_arm_weakspot',
                'signature': {'AV': 1,
                              'Dur%': 0,
                              'ExTarget': 'Main',
                              'MainCap': True,
                              'ToMain%': 0,
                              'health': 800},
                'raw_zone_name': '0x718ce684'},
               {'occurrence': 0,
                'zone_name': 'left_forearm',
                'signature': {'AV': 3,
                              'Dur%': 0.5,
                              'ExTarget': 'Main',
                              'MainCap': True,
                              'ToMain%': 0,
                              'health': 800},
                'raw_zone_name': '0x15b7e16d'},
               {'occurrence': 1,
                'zone_name': 'right_arm_weakspot',
                'signature': {'AV': 1,
                              'Dur%': 0,
                              'ExTarget': 'Main',
                              'MainCap': True,
                              'ToMain%': 0,
                              'health': 800},
                'raw_zone_name': '0x61dcc7a6'},
               {'occurrence': 1,
                'zone_name': 'right_forearm',
                'signature': {'AV': 3,
                              'Dur%': 0.5,
                              'ExTarget': 'Main',
                              'MainCap': True,
                              'ToMain%': 0,
                              'health': 800},
                'raw_zone_name': '0x20c2028d'},
               {'occurrence': 0,
                'zone_name': 'left_hip',
                'signature': {'AV': 2,
                              'Dur%': 0.5,
                              'ExTarget': 'Main',
                              'IsFatal': True,
                              'MainCap': False,
                              'ToMain%': 0.75,
                              'health': 1600},
                'raw_zone_name': 'left_hip'},
               {'occurrence': 1,
                'zone_name': 'left_upper_leg',
                'signature': {'AV': 2,
                              'Dur%': 0.5,
                              'ExTarget': 'Main',
                              'IsFatal': True,
                              'MainCap': False,
                              'ToMain%': 0.75,
                              'health': 1600},
                'raw_zone_name': '0x93c0058d'},
               {'occurrence': 2,
                'zone_name': 'right_hip',
                'signature': {'AV': 2,
                              'Dur%': 0.5,
                              'ExTarget': 'Main',
                              'IsFatal': True,
                              'MainCap': False,
                              'ToMain%': 0.75,
                              'health': 1600},
                'raw_zone_name': 'right_hip'},
               {'occurrence': 3,
                'zone_name': 'right_upper_leg',
                'signature': {'AV': 2,
                              'Dur%': 0.5,
                              'ExTarget': 'Main',
                              'IsFatal': True,
                              'MainCap': False,
                              'ToMain%': 0.75,
                              'health': 1600},
                'raw_zone_name': '0x56eb4767'},
               {'occurrence': 1,
                'zone_name': 'left_lower_leg',
                'signature': {'AV': 3,
                              'Dur%': 0.5,
                              'ExTarget': 'Main',
                              'IsFatal': True,
                              'MainCap': False,
                              'ToMain%': 0.75,
                              'health': 1600},
                'raw_zone_name': 'left_leg'},
               {'occurrence': 2,
                'zone_name': 'right_lower_leg',
                'signature': {'AV': 3,
                              'Dur%': 0.5,
                              'ExTarget': 'Main',
                              'IsFatal': True,
                              'MainCap': False,
                              'ToMain%': 0.75,
                              'health': 1600},
                'raw_zone_name': 'right_leg'},
               {'occurrence': 3,
                'zone_name': 'rear_hip',
                'signature': {'AV': 3,
                              'Dur%': 0.5,
                              'ExTarget': 'Main',
                              'IsFatal': True,
                              'MainCap': False,
                              'ToMain%': 0.75,
                              'health': 1600},
                'raw_zone_name': '0xb709fe1c',
                'raw_occurrence': 0},
               {'occurrence': 4,
                'zone_name': 'rear_leg',
                'signature': {'AV': 3,
                              'Dur%': 0.5,
                              'ExTarget': 'Main',
                              'IsFatal': True,
                              'MainCap': False,
                              'ToMain%': 0.75,
                              'health': 1600},
                'raw_zone_name': '0xb709fe1c',
                'raw_occurrence': 1},
               {'occurrence': 0,
                'zone_name': 'shield',
                'signature': {'AV': 2,
                              'Dur%': 0,
                              'ExTarget': 'Main',
                              'MainCap': True,
                              'ToMain%': 0,
                              'health': 1300},
                'raw_zone_name': 'shield'}]}
